"""empty message

Revision ID: 238923d996c0
Revises: 2f6b7a40642e
Create Date: 2015-07-26 14:58:45.031100

"""

# revision identifiers, used by Alembic.
revision = '238923d996c0'
down_revision = '2f6b7a40642e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('body', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'body')
    ### end Alembic commands ###
