"""empty message

Revision ID: 29b1f7984a47
Revises: 2d4f345b313e
Create Date: 2015-08-06 13:37:08.896271

"""

# revision identifiers, used by Alembic.
revision = '29b1f7984a47'
down_revision = '2d4f345b313e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('html', sa.UnicodeText(length=4294967295), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'html')
    ### end Alembic commands ###
