"""empty message

Revision ID: 2d4f345b313e
Revises: 238923d996c0
Create Date: 2015-07-26 15:07:26.071252

"""

# revision identifiers, used by Alembic.
revision = '2d4f345b313e'
down_revision = '238923d996c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
