"""empty message

Revision ID: 2f6b7a40642e
Revises: 214da3e5be1c
Create Date: 2015-07-26 10:58:03.379239

"""

# revision identifiers, used by Alembic.
revision = '2f6b7a40642e'
down_revision = '214da3e5be1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
