"""empty message

Revision ID: 3d16975099dc
Revises: 71e3de44de
Create Date: 2016-01-07 16:14:53.927272

"""

# revision identifiers, used by Alembic.
revision = '3d16975099dc'
down_revision = '71e3de44de'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('html', sa.UnicodeText(length=4294967295), nullable=True))
    op.add_column('document', sa.Column('meta_date', sa.String(length=256), nullable=True))
    op.add_column('document', sa.Column('meta_provenience', sa.String(length=256), nullable=True))
    op.add_column('document', sa.Column('meta_title', sa.String(length=256), nullable=True))
    op.drop_column('document', 'date')
    op.drop_column('document', 'provenience')
    op.drop_column('document', 'title')
    op.add_column('hand', sa.Column('hand_no', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hand', 'hand_no')
    op.add_column('document', sa.Column('title', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('document', sa.Column('provenience', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('document', sa.Column('date', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('document', 'meta_title')
    op.drop_column('document', 'meta_provenience')
    op.drop_column('document', 'meta_date')
    op.drop_column('document', 'html')
    ### end Alembic commands ###
