"""empty message

Revision ID: 410c00c6f288
Revises: 467c33bf821c
Create Date: 2016-05-31 11:29:30.387159

"""

# revision identifiers, used by Alembic.
revision = '410c00c6f288'
down_revision = '467c33bf821c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('type', mysql.VARCHAR(length=80), nullable=True))
    ### end Alembic commands ###
