"""empty message

Revision ID: 467c33bf821c
Revises: e442d1798da5
Create Date: 2016-05-31 09:45:43.856676

"""

# revision identifiers, used by Alembic.
revision = '467c33bf821c'
down_revision = 'e442d1798da5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document', sa.Column('type', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'type')
    op.drop_table('userdocument')
    ### end Alembic commands ###
