"""empty message

Revision ID: 578b96af6329
Revises: None
Create Date: 2017-01-09 14:39:23.748011

"""

# revision identifiers, used by Alembic.
revision = '578b96af6329'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hand', sa.Column('meta_addressee_trismegistos_id', sa.Integer(), nullable=True))
    op.add_column('hand', sa.Column('meta_author_trismegistos_id', sa.Integer(), nullable=True))
    op.add_column('hand', sa.Column('meta_scribal_trismegistos_id', sa.Integer(), nullable=True))
    op.add_column('hand', sa.Column('meta_writer_trismegistos_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hand', 'meta_writer_trismegistos_id')
    op.drop_column('hand', 'meta_scribal_trismegistos_id')
    op.drop_column('hand', 'meta_author_trismegistos_id')
    op.drop_column('hand', 'meta_addressee_trismegistos_id')
    ### end Alembic commands ###
