"""empty message

Revision ID: 5a2d577011a4
Revises: b343eea7c57b
Create Date: 2016-01-12 13:56:45.415725

"""

# revision identifiers, used by Alembic.
revision = '5a2d577011a4'
down_revision = 'b343eea7c57b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
