"""empty message

Revision ID: 5bba9eddf377
Revises: e08c4269e751
Create Date: 2017-02-24 14:34:09.884874

"""

# revision identifiers, used by Alembic.
revision = '5bba9eddf377'
down_revision = 'e08c4269e751'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hand', sa.Column('hand_name', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hand', 'hand_name')
    ### end Alembic commands ###
