"""empty message

Revision ID: 62a3369dcfa5
Revises: 7b54ab311317
Create Date: 2016-06-30 23:14:30.883272

"""

# revision identifiers, used by Alembic.
revision = '62a3369dcfa5'
down_revision = '7b54ab311317'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layertreebank', sa.Column('plaintext', sa.UnicodeText(length=4294967295), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layertreebank', 'plaintext')
    ### end Alembic commands ###
