"""empty message

Revision ID: 71e3de44de
Revises: 29b1f7984a47
Create Date: 2016-01-07 15:23:41.308692

"""

# revision identifiers, used by Alembic.
revision = '71e3de44de'
down_revision = '29b1f7984a47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('date', sa.String(length=256), nullable=True),
    sa.Column('provenience', sa.String(length=256), nullable=True),
    sa.Column('xml', sa.UnicodeText(length=4294967295), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('meta_handwriting_description_edition', sa.UnicodeText(), nullable=True),
    sa.Column('meta_handwriting_description_custom', sa.UnicodeText(), nullable=True),
    sa.Column('meta_handwriting_professional', sa.UnicodeText(), nullable=True),
    sa.Column('meta_handwriting_same_hand', sa.UnicodeText(), nullable=True),
    sa.Column('meta_writer_name', sa.UnicodeText(), nullable=True),
    sa.Column('meta_writer_title', sa.UnicodeText(), nullable=True),
    sa.Column('meta_scribal_name', sa.UnicodeText(), nullable=True),
    sa.Column('meta_scribal_title', sa.UnicodeText(), nullable=True),
    sa.Column('meta_author_name', sa.UnicodeText(), nullable=True),
    sa.Column('meta_author_title', sa.UnicodeText(), nullable=True),
    sa.Column('meta_text_type', sa.UnicodeText(), nullable=True),
    sa.Column('meta_addressee', sa.UnicodeText(), nullable=True),
    sa.Column('meta_addressee_name', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layertreebank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('hand_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.UnicodeText(length=4294967295), nullable=True),
    sa.Column('settings', sa.UnicodeText(length=4294967295), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hand_id'], ['hand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layertreebank')
    op.drop_table('hand')
    op.drop_table('document')
    ### end Alembic commands ###
