"""empty message

Revision ID: 7b54ab311317
Revises: e3581f5132a0
Create Date: 2016-06-09 12:41:52.046166

"""

# revision identifiers, used by Alembic.
revision = '7b54ab311317'
down_revision = 'e3581f5132a0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('message_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('document_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name='notification_ibfk_3'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='notification_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='notification_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
