"""empty message

Revision ID: 8fc57320760b
Revises: 6c80bc3e5c3f
Create Date: 2016-05-17 16:23:15.810581

"""

# revision identifiers, used by Alembic.
revision = '8fc57320760b'
down_revision = '6c80bc3e5c3f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treebank')
    op.drop_table('layer')
    op.drop_table('source')
    
    
    op.add_column('layertreebank', sa.Column('approved_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'layertreebank', 'user', ['approved_user_id'], ['id'])
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_constraint(None, 'layertreebank', type_='foreignkey')
    op.drop_column('layertreebank', 'approved_user_id')
    op.create_table('treebank',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('layer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], [u'layer.id'], name=u'treebank_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.create_table('layer',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('layer_type', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('source_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], [u'source.id'], name=u'layer_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.create_table('source',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('namespace', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('body', mysql.LONGTEXT(), nullable=True),
    sa.Column('html', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'source_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
