"""empty message

Revision ID: b343eea7c57b
Revises: 3d16975099dc
Create Date: 2016-01-10 18:35:25.557968

"""

# revision identifiers, used by Alembic.
revision = 'b343eea7c57b'
down_revision = '3d16975099dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
