"""empty message

Revision ID: e08c4269e751
Revises: e22bc80f6a19
Create Date: 2017-02-24 14:03:07.704927

"""

# revision identifiers, used by Alembic.
revision = 'e08c4269e751'
down_revision = 'e22bc80f6a19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_count', sa.Integer(), nullable=True),
    sa.Column('standard_count', sa.Integer(), nullable=True),
    sa.Column('variation_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    ### end Alembic commands ###
