"""empty message

Revision ID: e3581f5132a0
Revises: bf9273c4d80a
Create Date: 2016-06-08 13:26:13.488066

"""

# revision identifiers, used by Alembic.
revision = 'e3581f5132a0'
down_revision = 'bf9273c4d80a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification', 'document', ['document_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'document_id')
    ### end Alembic commands ###
