"""empty message

Revision ID: e442d1798da5
Revises: 8fc57320760b
Create Date: 2016-05-30 12:00:58.029449

"""

# revision identifiers, used by Alembic.
revision = 'e442d1798da5'
down_revision = '8fc57320760b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('meta_date_not_after', sa.String(length=256), nullable=True))
    op.add_column('document', sa.Column('meta_date_not_before', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'meta_date_not_before')
    op.drop_column('document', 'meta_date_not_after')
    ### end Alembic commands ###
